---

- name: Create /home/imgs directory
  file:
    path: /home/imgs
    owner: "{{ ansible_user }}"
    state: directory
    mode: 0755

- name: Create /home/pkgs directory
  file:
    path: /home/pkgs
    owner: "{{ ansible_user }}"
    state: directory
    mode: 0755

- name: Create /home/repos directory
  file:
    path: /home/repos
    owner: nd
    group: nd
    state: directory
    mode: 0755

- name: Create /var/www/doc.nextdeploy.io
  file:
    path: /var/www/doc.nextdeploy.io
    owner: nd
    group: nd
    state: directory
    mode: 0755

- name: Create /var/www/doc.nextdeploy.io/api
  file:
    path: /var/www/doc.nextdeploy.io/api
    owner: nd
    group: nd
    state: directory
    mode: 0755

- name: Create /var/www/doc.nextdeploy.io/webui
  file:
    path: /var/www/doc.nextdeploy.io/webui
    owner: nd
    group: nd
    state: directory
    mode: 0755

- name: Symbolic /var/www/doc.nextdeploy.io/api/code
  file:
    src: /home/repos/nextdeploy/ror/docs
    dest: /var/www/doc.nextdeploy.io/api/code
    state: link
    force: yes

- name: Symbolic /var/www/doc.nextdeploy.io/webui/code
  file:
    src: /home/repos/nextdeploy-webui/docs
    dest: /var/www/doc.nextdeploy.io/webui/code
    state: link
    force: yes

- name: Deploy nextdeploy.io repository
  git:
    repo: https://github.com/ricofehr/nextdeploy.io
    dest: /home/repos/nextdeploy.io
  become_user: nd
  notify:
    - build ndio

- name: Symbolic /var/www/doc.nextdeploy.io/webui/code
  file:
    src: /home/repos/nextdeploy.io/dist
    dest: /var/www/nextdeploy.io
    state: link
    force: yes

- name: Deploy nextdeploy repository
  git:
    repo: https://github.com/ricofehr/nextdeploy
    dest: /home/repos/nextdeploy
    recursive: no
  become_user: nd
  notify:
    - build doc nd

- name: Deploy nextdeploy-webui repository
  git:
    repo: https://github.com/ricofehr/nextdeploy-webui
    dest: /home/repos/nextdeploy-webui
  become_user: nd
  notify:
    - build doc webui

- name: Deploy nextdeploy-sop repository
  git:
    repo: https://github.com/ricofehr/nextdeploy-sop
    dest: /home/repos/nextdeploy-sop
  become_user: nd

- name: Deploy nd01 repository
  git:
    repo: https://github.com/ricofehr/ansible-nd01
    dest: /home/repos/ansible-nd01
  become_user: nd

- name: Create local inventory
  copy:
    content: |
             [nd]
             {{ inventory_hostname }}
    dest: /home/repos/ansible-nd01/inventory_local
    owner: nd
    group: nd
    mode: 0644

- name: Check if local secret file exists
  local_action: stat path=".vault_pass.txt"
  register: file
  become: no

- name: Copy local secret file to remote if exists
  copy:
    src: .vault_pass.txt
    dest: /home/repos/ansible-nd01/.vault_pass.txt
    owner: nd
    group: nd
    mode: 0600
  when: file.stat.exists

- name: Insert cron task for build ndio and generate doc
  cron:
    name: "build ndio and docs"
    user: nd
    minute: "*/30"
    hour: "*"
    job: "cd /home/repos/ansible-nd01 && ansible-playbook -i inventory_local nd.yml --vault-password-file=.vault_pass.txt"

- name: Sync local imgs repo to remote
  synchronize:
    src: assets/imgs/
    dest: /home/imgs/
    compress: no
    times: no
    # set_remote_user: yes
    # rsync_opts:
    #   - --ignore-existing
  become: no

- name: Sync local pkgs repo to remote
  synchronize:
    src: assets/pkgs/
    dest: /home/pkgs/
    times: no
    # set_remote_user: yes
    # rsync_opts:
    #   - --ignore-existing
  become: no
