---

- name: Create /home/repos directory
  file:
    path: /home/repos
    owner: nd
    group: nd
    state: directory
    mode: 0755
  become_user: root

- name: Create /var/www/doc.nextdeploy.io
  file:
    path: /var/www/doc.nextdeploy.io
    owner: nd
    group: nd
    state: directory
    mode: 0755
  become_user: root

- name: Create /var/www/doc.nextdeploy.io/api
  file:
    path: /var/www/doc.nextdeploy.io/api
    owner: nd
    group: nd
    state: directory
    mode: 0755
  become_user: root

- name: Create /var/www/doc.nextdeploy.io/webui
  file:
    path: /var/www/doc.nextdeploy.io/webui
    owner: nd
    group: nd
    state: directory
    mode: 0755
  become_user: root

- name: Symbolic /var/www/doc.nextdeploy.io/api/code
  file:
    src: /home/repos/nextdeploy/ror/docs
    dest: /var/www/doc.nextdeploy.io/api/code
    state: link
    force: yes

- name: Symbolic /var/www/doc.nextdeploy.io/webui/code
  file:
    src: /home/repos/nextdeploy-webui/docs
    dest: /var/www/doc.nextdeploy.io/webui/code
    state: link
    force: yes

- name: Deploy nextdeploy.io repository
  git:
    repo: https://github.com/ricofehr/nextdeploy.io
    dest: /home/repos/nextdeploy.io
  register: ndio_update
  notify:
    - build ndio

- name: Deploy nextdeploy repository
  git:
    repo: https://github.com/ricofehr/nextdeploy
    dest: /home/repos/nextdeploy
    recursive: no
  register: nd_update
  notify:
    - build doc nd

- name: Deploy nextdeploy-webui repository
  git:
    repo: https://github.com/ricofehr/nextdeploy-webui
    dest: /home/repos/nextdeploy-webui
  register: ndwebui_update
  notify:
    - build doc webui

- name: Deploy nextdeploy-sop repository
  git:
    repo: https://github.com/ricofehr/nextdeploy-sop
    dest: /home/repos/nextdeploy-sop

- name: Deploy nd01 repository
  git:
    repo: https://github.com/ricofehr/ansible-nd01
    dest: /home/repos/ansible-nd01

- name: Create local inventory
  copy:
    content: |
             [nd]
             {{ inventory_hostname }}
    dest: /home/repos/ansible-nd01/inventory_local

- name: Check if local secret file exists
  local_action: stat path=".vault_pass.txt"
  register: file
  become: no
  sudo: no

- name: Copy local secret file to remote if exists
  copy:
    src: .vault_pass.txt
    dest: /home/repos/ansible-nd01/.vault_pass.txt
    owner: nd
    group: nd
    mode: 0600
  become_user: root
  when: file.stat.exists

- name: Insert cron task for build ndio and generate doc
  cron:
    name: "build ndio and docs"
    minute: "*/30"
    hour: "*"
    job: "cd /home/repos/ansible-nd01 && ansible-playbook -i inventory_local nd.yml --vault-password-file=.vault_pass.txt"

- name: check if imgs repo exists
  local_action: stat path="assets/imgs"
  register: folder
  become: no
  sudo: no

- name: copy local imgs repo to remote if exists
  copy:
    src: assets/imgs
    dest: /home/imgs
    owner: nd
    group: nd
    mode: 0755
  become_user: root
  when: folder.stat.exists

- name: check if pkgs repo exists
  local_action: stat path="assets/pkgs"
  register: folder
  become: no
  sudo: no

- name: copy local pkgs repo to remote if exists
  copy:
    src: assets/pkgs
    dest: /home/pkgs
    owner: nd
    group: nd
    mode: 0755
  become_user: root
  when: folder.stat.exists

- name: check if jenkins jobs repo exists
  local_action: stat path="assets/jobs"
  register: folder
  become: no
  sudo: no

- name: copy local jobs repo to remote if exists
  copy:
    src: assets/jobs
    dest: /var/lib/jenkins/jobs
    owner: jenkins
    group: jenkins
    mode: 0775
  become_user: root
  when: folder.stat.exists
