---

- hosts: nd
  serial: 1
  max_fail_percentage: 0
  become: yes
  roles:
   - role: ssh-hardening
     tags: ['ssh']
   - base
   - keyboard
   - apt
   - ntp
   - git
   - vagrant
   - ansible
   - nodejs
   - ruby
   - nginx
   - vsftpd
   - jenkins
   - ndjobs
   - repos
   - elasticsearch
   - logstash
   - kibana
   - role: openvpn
     tags:
       - vpn
