---

- name: build ndio
  shell: export PATH=$PATH:/home/nd/npm/bin;npm install; bower install; ember build -e production
  args:
    chdir: /home/repos/nextdeploy.io
    executable: /bin/bash
  become_user: nd

- name: build doc nd
  shell: bundle install;sudo -u nd yardoc lib/**/*.rb app/**/*.rb config/**/*.rb lib/*.rb app/**/api/v1/*.rb
  args:
    chdir: /home/repos/nextdeploy/ror
    executable: /bin/bash

- name: build doc webui
  shell: export PATH=$PATH:/home/nd/npm/bin;npm install; bower install; ember ember-cli-yuidoc
  args:
    chdir: /home/repos/nextdeploy-webui
    executable: /bin/bash
  become_user: nd
